// GET EFFORT CHARTS
export const GET_EFFORT_REQ = "GET_EFFORT_REQ";

export const GET_EFFORT_SUCESS = "GET_EFFORT_SUCESS";

export const GET_EFFORT_FAILED = "GET_EFFORT_FAILED";


//GET EXECUTION OVERVIEW CHARTS
export const GET_EXEC_OVERVIEW_REQ = "GET_EXEC_OVERVIEW_REQ";

export const GET_EXEC_OVERVIEW_SUCESS = "GET_EXEC_OVERVIEW_SUCESS";

export const GET_EXEC_OVERVIEW_FAILED = "GET_EXEC_OVERVIEW_FAILED";


//GET MULTI CHARTS
export const GET_MULTI_CHART_REQ = "GET_MULTI_CHART_REQ";

export const GET_MULTI_CHART_SUCESS = "GET_MULTI_CHART_SUCESS";

export const GET_MULTI_CHART_FAILED= "GET_MULTI_CHART_FAILED";

//GET SIX EXECUTION

export const GET_SIX_EXECUTION_REQ = "GET_SIX_EXECUTION_REQ";

export const GET_SIX_EXECUTION_SUCESS = "GET_SIX_EXECUTION_SUCESS";

export const GET_SIX_EXECUTION_FAILED = "GET_SIX_EXECUTION_FAILED";