// GET IMAGE
export const GET_IMAGE_REQ = "GET_IMAGE_REQ";

export const GET_IMAGE_SUCCESS = "GET_IMAGE_SUCCESS";

export const GET_IMAGE_FAILED = "GET_IMAGE_FAILED";

// UPLOAD IMAGE

export const UPLOAD_IMAGE_REQ = "UPLOAD_IMAGE_REQ";

export const UPLOAD_IMAGE_SUCCESS = "UPLOAD_IMAGE_SUCCESS";

export const UPLOAD_IMAGE_FAILED = "UPLOAD_IMAGE_FAILED";

export const RESET_UPLOAD_IMAGE = "RESET_UPLOAD_IMAGE";