// GET ALL USERS REQ
export const GET_ALL_USERS_REQ = "GET_ALL_USERS_REQ";

export const GET_ALL_USERS_SUCCESS = "GET_ALL_USERS_SUCCESS";

export const GET_ALL_USERS_FAILED = "GET_ALL_USERS_FAILED";

// ADD USERS TO PROJECT REQ
export const ADD_USERS_TO_PROJECT_REQ = "ADD_USERS_TO_PROJECT_REQ";

export const ADD_USERS_TO_PROJECT_SUCCESS = "ADD_USERS_TO_PROJECT_SUCCESS";

export const ADD_USERS_TO_PROJECT_FAILED = "ADD_USERS_TO_PROJECT_FAILED";

// GET ALL USERS OF PROJECT REQ
export const GET_ALL_USERS_OF_PROJECT_REQ = "GET_ALL_USERS_OF_PROJECT_REQ";

export const GET_ALL_USERS_OF_PROJECT_SUCCESS = "GET_ALL_USERS_OF_PROJECT_SUCCESS";

export const GET_ALL_USERS_OF_PROJECT_FAILED = "GET_ALL_USERS_OF_PROJECT_FAILED";

//SELECT A USERS
export const SELECT_USER = "SELECT_USER";

//CREATE A NEW USER
export const ADD_NEW_USER_REQ = "ADD_NEW_USER_REQ";

export const ADD_NEW_USER_SUCCESS = "ADD_NEW_USER_SUCCESS";

export const ADD_NEW_USER_FAILED = "ADD_NEW_USER_FAILED";

//UPDATE A NEW USER
export const UPDATE_USER_REQ = "UPDATE_USER_REQ";

export const UPDATE_USER_SUCCESS = "UPDATE_USER_SUCCESS";

export const UPDATE_USER_FAILED = "UPDATE_USER_FAILED";

//DELETE USER
export const DELETE_USER_REQ = "DELETE_USER_REQ";

export const DELETE_USER_SUCCESS = "DELETE_USER_SUCCESS";

export const DELETE_USER_FAILED = "DELETE_USER_FAILED";

//GET USER BY ID
export const GET_USER_BYID_REQ = "GET_USER_BYID_REQ";

export const GET_USER_BYID_SUCCESS = "GET_USER_BYID_SUCCESS";

export const GET_USER_BYID_FAILED = "GET_USER_BYID_FAILED";

//DELETE USER OF PROJECT
export const DELETE_USER_OF_PROJECT_REQ = "DELETE_USER_OF_PROJECT_REQ";

export const DELETE_USER_OF_PROJECT_SUCCESS = "DELETE_USER_OF_PROJECT_SUCCESS";

export const DELETE_USER_OF_PROJECT_FAILED = "DELETE_USER_OF_PROJECT_FAILED";

//UPDATE PASSWORD
export const UPDATE_PASSWORD_REQ = "UPDATE_PASSWORD_REQ";

export const UPDATE_PASSWORD_SUCCESS = "UPDATE_PASSWORD_SUCCESS";

export const UPDATE_PASSWORD_FAILED = "UPDATE_PASSWORD_FAILED";

//UPDATE PROFILE
export const UPDATE_PROFILE_REQ = "UPDATE_PROFILE_REQ";

export const UPDATE_PROFILE_SUCCESS = "UPDATE_PROFILE_SUCCESS";

export const UPDATE_PROFILE_FAILED = "UPDATE_PROFILE_FAILED";

//GET CURRENT USER
export const GET_CURRENT_USER_REQ = "GET_CURRENT_USER_REQ";

export const GET_CURRENT_USER_SUCCESS = "GET_CURRENT_USER_SUCCESS";

export const GET_CURRENT_USER_FAILED = "GET_CURRENT_USER_FAILED";
