// GET ALL ISSUE REQ
export const GET_ALL_ISSUE_REQ = "GET_ALL_ISSUE_REQ";

export const GET_ALL_ISSUE_SUCESS = "GET_ALL_ISSUE_SUCESS";

export const GET_ALL_ISSUE_FAILED = "GET_ALL_ISSUE_FAILED";

// CREATE ISSUE
export const CREATE_ISSUE_REQ = "CREATE_ISSUE_REQ";

export const CREATE_ISSUE_SUCCESS = "CREATE_ISSUE_SUCCESS";

export const CREATE_ISSUE_FAILED = "CREATE_ISSUE_FAILED";

export const RESET_CREATE_ISSUE = "RESET_CREATE_ISSUE";

//SELECT A ISSUE
export const SELECT_ISSUE = "SELECT_ISSUE";

//UPDATE ISSUE
export const UPDATE_ISSUE_REQ = "UPDATE_ISSUE_REQ";

export const UPDATE_ISSUE_SUCCESS = "UPDATE_ISSUE_SUCCESS";

export const UPDATE_ISSUE_FAILED = "UPDATE_ISSUE_FAILED";

export const RESET_UPDATE_ISSUE = "RESET_UPDATE_ISSUE";

//DELETE ISSUE
export const DELETE_ISSUE_REQ = "DELETE_ISSUE_REQ";

export const DELETE_ISSUE_SUCCESS = "DELETE_ISSUE_SUCCESS";

export const DELETE_ISSUE_FAILED = "DELETE_ISSUE_FAILED";

export const RESET_DELETE_ISSUE = "RESET_DELETE_ISSUE";


//GET CATEGORY
export const GET_ALL_CATEGORY_REQ = "GET_ALL_CATEGORY_REQ";

export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";

export const GET_ALL_CATEGORY_FAILED = "GET_ALL_CATEGORY_FAILED";

//ADD CATEGORY
export const ADD_CATEGORY_REQ = "ADD_CATEGORY_REQ";

export const ADD_CATEGORY_SUCCESS = "ADD_CATEGORY_SUCCESS";

export const ADD_CATEGORY_FAILED = "ADD_CATEGORY_FAILED";

export const RESET_ADD_CATEGORY = "RESET_ADD_CATEGORY";

//REMOVE CATEGORY
export const REMOVE_CATEGORY_REQ = "REMOVE_CATEGORY_REQ";

export const REMOVE_CATEGORY_SUCCESS = "REMOVE_CATEGORY_SUCCESS";

export const REMOVE_CATEGORY_FAILED = "REMOVE_CATEGORY_FAILED";

export const RESET_REMOVE_CATEGORY = "RESET_REMOVE_CATEGORY";
