// Mantis redux below
// GET ALL ISSUE REQ
export const GET_ALL_ISSUE_REQ = "GET_ALL_ISSUE_REQ";

export const GET_ALL_ISSUE_SUCESS = "GET_ALL_ISSUE_SUCESS";

export const GET_ALL_ISSUE_FAILED = "GET_ALL_ISSUE_FAILED";

// CREATE ISSUE
export const CREATE_ISSUE_REQ = "CREATE_ISSUE_REQ";

export const CREATE_ISSUE_SUCCESS = "CREATE_ISSUE_SUCCESS";

export const CREATE_ISSUE_FAILED = "CREATE_ISSUE_FAILED";

export const RESET_CREATE_ISSUE = "RESET_CREATE_ISSUE";

//SELECT A ISSUE
export const SELECT_ISSUE = "SELECT_ISSUE";

//UPDATE ISSUE
export const UPDATE_ISSUE_REQ = "UPDATE_ISSUE_REQ";

export const UPDATE_ISSUE_SUCCESS = "UPDATE_ISSUE_SUCCESS";

export const UPDATE_ISSUE_FAILED = "UPDATE_ISSUE_FAILED";

export const RESET_UPDATE_ISSUE = "RESET_UPDATE_ISSUE";

//DELETE ISSUE
export const DELETE_ISSUE_REQ = "DELETE_ISSUE_REQ";

export const DELETE_ISSUE_SUCCESS = "DELETE_ISSUE_SUCCESS";

export const DELETE_ISSUE_FAILED = "DELETE_ISSUE_FAILED";

export const RESET_DELETE_ISSUE = "RESET_DELETE_ISSUE";

//DELETE ISSUE FROM EXEC
export const DELETE_ISSUE_FROM_EXEC_REQ = "DELETE_ISSUE_FROM_EXEC_REQ";

export const DELETE_ISSUE_FROM_EXEC_SUCCESS = "DELETE_ISSUE_FROM_EXEC_SUCCESS";

export const DELETE_ISSUE_FROM_EXEC_FAILED = "DELETE_ISSUE_FROM_EXEC_FAILED";

export const RESET_DELETE_ISSUE_FROM_EXEC = "RESET_DELETE_ISSUE_FROM_EXEC";


//GET CATEGORY
export const GET_ALL_CATEGORY_REQ = "GET_ALL_CATEGORY_REQ";

export const GET_ALL_CATEGORY_SUCCESS = "GET_ALL_CATEGORY_SUCCESS";

export const GET_ALL_CATEGORY_FAILED = "GET_ALL_CATEGORY_FAILED";

//ADD ISSUE FROM URL
export const ADD_ISSUE_REQ = "ADD_ISSUE_REQ";

export const ADD_ISSUE_SUCCESS = "ADD_ISSUE_SUCCESS";

export const ADD_ISSUE_FAILED = "ADD_ISSUE_FAILED";

export const RESET_ADD_ISSUE = "RESET_ADD_ISSUE";

//=====================* MANTIS *======================

// CREATE MANTIS
export const CREATE_NEW_MANTIS_REQ = "CREATE_NEW_MANTIS_REQ";

export const CREATE_NEW_MANTIS_SUCCESS = "CREATE_NEW_MANTIS_SUCCESS";

export const CREATE_NEW_MANTIS_FAILED = "CREATE_NEW_MANTIS_FAILED";

export const RESET_CREATE_NEW_MANTIS = "RESET_CREATE_NEW_MANTIS";

// GET INFO MANTIS
export const GET_INFO_MANTIS_REQ = "GET_INFO_MANTIS_REQ";

export const GET_INFO_MANTIS_SUCCESS = "GET_INFO_MANTIS_SUCCESS";

export const GET_INFO_MANTIS_FAILED = "GET_INFO_MANTIS_FAILED";

export const RESET_GET_INFO_MANTIS = "RESET_GET_INFO_MANTIS";

// GET ALL MANTIS OF PROJECT
export const GET_ALL_MANTIS_OF_PROJECT_REQ = "GET_ALL_MANTIS_OF_PROJECT_REQ";

export const GET_ALL_MANTIS_OF_PROJECT_SUCCESS = "GET_ALL_MANTIS_OF_PROJECT_SUCCESS";

export const GET_ALL_MANTIS_OF_PROJECT_FAILED = "GET_ALL_MANTIS_OF_PROJECT_FAILED";

// GET ALL MANTIS URL CONNECTED TO PROJECT
export const GET_ALL_CONNECTED_MANTIS_REQ = "GET_ALL_CONNECTED_MANTIS_REQ";

export const GET_ALL_CONNECTED_MANTIS_SUCCESS = "GET_ALL_CONNECTED_MANTIS_SUCCESS";

export const GET_ALL_CONNECTED_MANTIS_FAILED = "GET_ALL_CONNECTED_MANTIS_FAILED";


// SWITCH CONNECTED MANTIS
export const SWITCH_CONNECTED_MANTIS_REQ = "SWITCH_CONNECTED_MANTIS_REQ";

export const SWITCH_CONNECTED_MANTIS_SUCCESS = "SWITCH_CONNECTED_MANTIS_SUCCESS";

export const SWITCH_CONNECTED_MANTIS_FAILED = "SWITCH_CONNECTED_MANTIS_FAILED";

export const RESET_SWITCH_CONNECTED_MANTIS = "RESET_SWITCH_CONNECTED_MANTIS";


// CREATE AND SWITCH MANTIS
export const CREATE_AND_SWITCH_MANTIS_REQ = "CREATE_AND_SWITCH_MANTIS_REQ";

export const CREATE_AND_SWITCH_MANTIS_SUCCESS = "CREATE_AND_SWITCH_MANTIS_SUCCESS";

export const CREATE_AND_SWITCH_MANTIS_FAILED = "CREATE_AND_SWITCH_MANTIS_FAILED";

export const RESET_CREATE_AND_SWITCH_MANTIS = "RESET_CREATE_AND_SWITCH_MANTIS";

// SWITCH MANTIS
export const SWITCH_MANTIS_REQ = "SWITCH_MANTIS_REQ";

export const SWITCH_MANTIS_SUCCESS = "SWITCH_MANTIS_SUCCESS";

export const SWITCH_MANTIS_FAILED = "SWITCH_MANTIS_FAILED";

export const RESET_SWITCH_MANTIS = "RESET_SWITCH_MANTIS";

// CHANGE API KEY
export const CHANGE_API_KEY_REQ = "CHANGE_API_KEY_REQ";

export const CHANGE_API_KEY_SUCCESS = "CHANGE_API_KEY_SUCCESS";

export const CHANGE_API_KEY_FAILED = "CHANGE_API_KEY_FAILED";

export const RESET_CHANGE_API_KEY = "RESET_CHANGE_API_KEY";