// GET ALL ISSUE REQ
export const GET_ALL_ISSUE_REQ = "GET_ALL_ISSUE_REQ";

export const GET_ALL_ISSUE_SUCESS = "GET_ALL_ISSUE_SUCESS";

export const GET_ALL_ISSUE_FAILED = "GET_ALL_ISSUE_FAILED";

//SELECT A ISSUE
export const SELECT_ISSUE = "SELECT_ISSUE";

//UPDATE ISSUE
export const UPDATE_ISSUE_REQ = "UPDATE_ISSUE_REQ";

export const UPDATE_ISSUE_SUCCESS = "UPDATE_ISSUE_SUCCESS";

export const UPDATE_ISSUE_FAILED = "UPDATE_ISSUE_FAILED";

export const RESET_UPDATE_ISSUE = "RESET_UPDATE_ISSUE";

//DELETE ISSUE
export const DELETE_ISSUE_REQ = "DELETE_ISSUE_REQ";

export const DELETE_ISSUE_SUCCESS = "DELETE_ISSUE_SUCCESS";

export const DELETE_ISSUE_FAILED = "DELETE_ISSUE_FAILED";

export const RESET_DELETE_ISSUE = "RESET_DELETE_ISSUE";