// GET ALL BUILDS REQ
export const GET_ALL_BUILDS_REQ = "GET_ALL_BUILDS_REQ";

export const GET_ALL_BUILDS_SUCCESS = "GET_ALL_BUILDS_SUCCESS";

export const GET_ALL_BUILDS_FAILED = "GET_ALL_BUILDS_FAILED";

// GET BUILD REPORT REQ
export const GET_BUILD_REPORT_REQ = "GET_BUILD_REPORT_REQ";

export const GET_BUILD_REPORT_SUCCESS = "GET_BUILD_REPORT_SUCCESS";

export const GET_BUILD_REPORT_FAILED = "GET_BUILD_REPORT_FAILED";

//SELECT A BUILD
export const SELECT_BUILD = "SELECT_BUILD";

//CREATE A NEW BUILD
export const ADD_NEW_BUILD_REQ = "ADD_NEW_BUILD_REQ";

export const ADD_NEW_BUILD_SUCCESS = "ADD_NEW_BUILD_SUCCESS";

export const ADD_NEW_BUILD_FAILED = "ADD_NEW_BUILD_FAILED";

export const RESET_ADD_NEW_BUILD = "RESET_ADD_NEW_BUILD";


//UPDATE A NEW BUILD
export const UPDATE_BUILD_REQ = "UPDATE_BUILD_REQ";

export const UPDATE_BUILD_SUCCESS = "UPDATE_BUILD_SUCCESS";

export const UPDATE_BUILD_FAILED = "UPDATE_BUILD_FAILED";

export const RESET_UPDATE_BUILD = "RESET_UPDATE_BUILD";


//DELETE A NEW BUILD
export const DELETE_BUILD_REQ = "DELETE_BUILD_REQ";

export const DELETE_BUILD_SUCCESS = "DELETE_BUILD_SUCCESS";

export const DELETE_BUILD_FAILED = "DELETE_BUILD_FAILED";

export const RESET_DELETE_BUILD = "RESET_DELETE_BUILD";


//GET BUILD BY ID
export const GET_BUILD_BYID_REQ = "GET_BUILD_BYID_REQ";

export const GET_BUILD_BYID_SUCCESS = "GET_BUILD_BYID_SUCCESS";

export const GET_BUILD_BYID_FAILED = "GET_BUILD_BYID_FAILED";


// GET ALL BUILD ACTIVE REQ
export const GET_ALL_BUILD_ACTIVE_REQ = "GET_ALL_BUILD_ACTIVE_REQ";

export const GET_ALL_BUILD_ACTIVE_SUCCESS = "GET_ALL_BUILD_ACTIVE_SUCCESS";

export const GET_ALL_BUILD_ACTIVE_FAILED = "GET_ALL_BUILD_ACTIVE_FAILED";

export const RESET_BUILD_ACTIVE = 'RESET_BUILD_ACTIVE';


// GET ALL BUILD ACTIVE BY TESTPLAN
export const GET_ALL_BUILD_TESTPLAN_REQ = "GET_ALL_BUILD_TESTPLAN_REQ";

export const GET_ALL_BUILD_TESTPLAN_SUCCESS = "GET_ALL_BUILD_TESTPLAN_SUCCESS";

export const GET_ALL_BUILD_TESTPLAN_FAILED = "GET_ALL_BUILD_TESTPLAN_FAILED";

export const RESET_BUILD_TESTPLAN = 'RESET_BUILD_TESTPLAN';
