// GET ALL BUILDS REQ
export const GET_ALL_BUILD_REQ = "GET_ALL_BUILD_REQ";

export const GET_ALL_BUILD_SUCESS = "GET_ALL_BUILD_SUCESS";

export const GET_ALL_BUILD_FAILED = "GET_ALL_BUILD_FAILED";

//SELECT A TESTPLAN
export const SELECT_BUILD = "SELECT_BUILD";

//CREATE A NEW TESTPLAN
export const ADD_NEW_BUILD_REQ = "ADD_NEW_BUILD_REQ";

export const ADD_NEW_BUILD_SUCCESS = "ADD_NEW_BUILD_SUCCESS";

export const ADD_NEW_BUILD_FAILED = "ADD_NEW_BUILD_FAILED";