// GET ALL TESTEXEC REQ
export const GET_ALL_TESTEXEC_REQ = "GET_ALL_TESTEXEC_REQ";

export const GET_ALL_TESTEXEC_SUCESS = "GET_ALL_TESTEXEC_SUCESS";

export const GET_ALL_TESTEXEC_FAILED = "GET_ALL_TESTEXEC_FAILED";

//ADD NEW TESTEXEC REQ
export const ADD_TESTEXEC_REQ = "ADD_TESTEXEC_REQ";

export const ADD_TESTEXEC_SUCCESS = "ADD_TESTEXEC_SUCCESS";

export const ADD_TESTEXEC_FAILED = "ADD_TESTEXEC_FAILED";


//EXECUTE TESTCASE
export const EXECUTE_TEST_CASE_REQ = "EXECUTE_TEST_CASE_REQ";

export const EXECUTE_TEST_CASE_SUCCESS = "EXECUTE_TEST_CASE_SUCCESS";

export const EXECUTE_TEST_CASE_FAILED = "EXECUTE_TEST_CASE_FAILED";