// GET ALL TESTEXEC REQ
export const GET_ALL_TESTEXEC_REQ = "GET_ALL_TESTEXEC_REQ";

export const GET_ALL_TESTEXEC_SUCESS = "GET_ALL_TESTEXEC_SUCESS";

export const GET_ALL_TESTEXEC_FAILED = "GET_ALL_TESTEXEC_FAILED";


//ADD NEW TESTEXEC REQ
export const ADD_TESTEXEC_REQ = "ADD_TESTEXEC_REQ";

export const ADD_TESTEXEC_SUCCESS = "ADD_TESTEXEC_SUCCESS";

export const ADD_TESTEXEC_FAILED = "ADD_TESTEXEC_FAILED";

export const RESET_ADD_TEST_EXEC = "RESET_ADD_TEST_EXEC";


//EXECUTE TESTCASE
export const EXECUTE_TEST_CASE_REQ = "EXECUTE_TEST_CASE_REQ";

export const EXECUTE_TEST_CASE_SUCCESS = "EXECUTE_TEST_CASE_SUCCESS";

export const EXECUTE_TEST_CASE_FAILED = "EXECUTE_TEST_CASE_FAILED";

export const RESET_EXECUTE_TEST_CASE = 'RESET_EXECUTE_TEST_CASE';


//UPDATE TEST EXEC
export const UPDATE_TEST_EXEC_REQ = "UPDATE_TEST_EXEC_REQ";

export const UPDATE_TEST_EXEC_SUCCESS = "UPDATE_TEST_EXEC_SUCCESS";

export const UPDATE_TEST_EXEC_FAILED = "UPDATE_TEST_EXEC_FAILED";

export const RESET_UPDATE_TEST_EXEC = 'RESET_UPDATE_TEST_EXEC';


//DELETE TEST EXEC
export const DELETE_TEST_EXEC_REQ = "DELETE_TEST_EXEC_REQ";

export const DELETE_TEST_EXEC_SUCCESS = "DELETE_TEST_EXEC_SUCCESS";

export const DELETE_TEST_EXEC_FAILED = "DELETE_TEST_EXEC_FAILED";

export const RESET_DELETE_TEST_EXEC = 'RESET_DELETE_TEST_EXEC';


//SELECT TEST EXEC
export const SELECT_TEST_EXEC_REQ = "SELECT_TEST_EXEC_REQ";

//SELECT TEST CASE
export const SELECT_TEST_CASE_REQ = "SELECT_TEST_CASE_REQ"

//SELECT REQUIREMENTS

//UPDATE TEST EXEC
export const UPDATE_TEST_EXEC_DETAIL_REQ = "UPDATE_TEST_EXEC_DETAIL_REQ";

export const UPDATE_TEST_EXEC_DETAIL_SUCCESS = "UPDATE_TEST_EXEC_DETAIL_SUCCESS";

export const UPDATE_TEST_EXEC_DETAIL_FAILED = "UPDATE_TEST_EXEC_DETAIL_FAILED";

export const RESET_UPDATE_TEST_EXEC_DETAIL = 'RESET_UPDATE_TEST_EXEC_DETAIL';

