// GET ALL REQUIREMENTS REQ
export const GET_ALL_REQUIREMENTS_REQ = "GET_ALL_REQUIREMENTS_REQ";

export const GET_ALL_REQUIREMENTS_SUCESS = "GET_ALL_REQUIREMENTS_SUCESS";

export const GET_ALL_REQUIREMENTS_FAILED = "GET_ALL_REQUIREMENTS_FAILED";

//SELECT A REQUIREMENTS
export const SELECT_REQUIREMENTS = "SELECT_REQUIREMENTS";

//CREATE A NEW REQUIREMENTS
export const ADD_NEW_REQUIREMENTS_REQ = "ADD_NEW_REQUIREMENTS_REQ";

export const ADD_NEW_REQUIREMENTS_SUCCESS = "ADD_NEW_REQUIREMENTS_SUCCESS";

export const ADD_NEW_REQUIREMENTS_FAILED = "ADD_NEW_REQUIREMENTS_FAILED";

export const RESET_ADD_NEW_REQUIREMENTS = "RESET_ADD_NEW_REQUIREMENTS";

//UPDATE REQUIREMENTS
export const UPDATE_REQUIREMENTS_REQ = "UPDATE_REQUIREMENTS_REQ";

export const UPDATE_REQUIREMENTS_SUCCESS = "UPDATE_REQUIREMENTS_SUCCESS";

export const UPDATE_REQUIREMENTS_FAILED = "UPDATE_REQUIREMENTS_FAILED";

export const RESET_UPDATE_REQUIREMENTS = "RESET_UPDATE_REQUIREMENTS";

// GET ALL ACTIVE_REQUIREMENTS REQ
export const GET_ALL_ACTIVE_REQUIREMENTS_REQ = "GET_ALL_ACTIVE_REQUIREMENTS_REQ";

export const GET_ALL_ACTIVE_REQUIREMENTS_SUCESS = "GET_ALL_ACTIVE_REQUIREMENTS_SUCESS";

export const GET_ALL_ACTIVE_REQUIREMENTS_FAILED = "GET_ALL_ACTIVE_REQUIREMENTS_FAILED";

//DELETE REQUIREMENTS
export const DELETE_REQUIREMENTS_REQ = "DELETE_REQUIREMENTS_REQ";

export const DELETE_REQUIREMENTS_SUCCESS = "DELETE_REQUIREMENTS_SUCCESS";

export const DELETE_REQUIREMENTS_FAILED = "DELETE_REQUIREMENTS_FAILED";

export const RESET_DELETE_REQUIREMENTS = "RESET_DELETE_REQUIREMENTS";