// GET ALL PROJECTS REQ
export const GET_ALL_PROJECTS_REQ = "GET_ALL_PROJECTS_REQ";

export const GET_ALL_PROJECTS_SUCESS = "GET_ALL_PROJECTS_SUCESS";

export const GET_ALL_PROJECTS_FAILED = "GET_ALL_PROJECTS_FAILED";

//SELECT A PROJECT
export const SELECT_PROJECT = "SELECT_PROJECT";

//CREATE A NEW PROJECT
export const ADD_NEW_PROJECT_REQ = "ADD_NEW_PROJECT_REQ";

export const ADD_NEW_PROJECT_SUCCESS = "ADD_NEW_PROJECT_SUCCESS";

export const ADD_NEW_PROJECT_FAILED = "ADD_NEW_PROJECT_FAILED";

//UPDATE PROJECT
export const UPDATE_PROJECT_REQ = "UPDATE_PROJECT_REQ";

export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";

export const UPDATE_PROJECT_FAILED = "UPDATE_PROJECT_FAILED";

//DELETE PROJECT
export const DELETE_PROJECT_REQ = "DELETE_PROJECT_REQ";

export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";

export const DELETE_PROJECT_FAILED = "DELETE_PROJECT_FAILED";