// GET ALL PROJECTS REQ
export const GET_ALL_PROJECTS_REQ = "GET_ALL_PROJECTS_REQ";

export const GET_ALL_PROJECTS_SUCESS = "GET_ALL_PROJECTS_SUCESS";

export const GET_ALL_PROJECTS_FAILED = "GET_ALL_PROJECTS_FAILED";

//SELECT A PROJECT
export const SELECT_PROJECT = "SELECT_PROJECT";