// GET ALL PROJECTS REQ
export const GET_ALL_PROJECTS_REQ = "GET_ALL_PROJECTS_REQ";

export const GET_ALL_PROJECTS_SUCESS = "GET_ALL_PROJECTS_SUCESS";

export const GET_ALL_PROJECTS_FAILED = "GET_ALL_PROJECTS_FAILED";

// GET ALL PROJECTS REQ
export const GET_PROJECTS_BY_ID_REQ = "GET_PROJECTS_BY_ID_REQ";

export const GET_PROJECTS_BY_ID_SUCESS = "GET_PROJECTS_BY_ID_SUCESS";

export const GET_PROJECTS_BY_ID_FAILED = "GET_PROJECTS_BY_ID_FAILED";

//SELECT A PROJECT
export const SELECT_PROJECT = "SELECT_PROJECT";

//CREATE A NEW PROJECT
export const ADD_NEW_PROJECT_REQ = "ADD_NEW_PROJECT_REQ";

export const ADD_NEW_PROJECT_SUCCESS = "ADD_NEW_PROJECT_SUCCESS";

export const ADD_NEW_PROJECT_FAILED = "ADD_NEW_PROJECT_FAILED";

export const RESET_ADD_NEW_PROJECT = "RESET_ADD_NEW_PROJECT";


//UPDATE PROJECT
export const UPDATE_PROJECT_REQ = "UPDATE_PROJECT_REQ";

export const UPDATE_PROJECT_SUCCESS = "UPDATE_PROJECT_SUCCESS";

export const UPDATE_PROJECT_FAILED = "UPDATE_PROJECT_FAILED";

export const RESET_UPDATE_PROJECT = "RESET_UPDATE_PROJECT";


//DELETE PROJECT
export const DELETE_PROJECT_REQ = "DELETE_PROJECT_REQ";

export const DELETE_PROJECT_SUCCESS = "DELETE_PROJECT_SUCCESS";

export const DELETE_PROJECT_FAILED = "DELETE_PROJECT_FAILED";

export const RESET_DELETE_PROJECT = "RESET_DELETE_PROJECT";

//DELETE PROJECT
export const CHANGE_ROLE_MEMBER_REQ = "CHANGE_ROLE_MEMBER_REQ";

export const CHANGE_ROLE_MEMBER_SUCCESS = "CHANGE_ROLE_MEMBER_SUCCESS";

export const CHANGE_ROLE_MEMBER_FAILED = "CHANGE_ROLE_MEMBER_FAILED";

export const RESET_CHANGE_ROLE_MEMBER = "RESET_CHANGE_ROLE_MEMBER";

//RESET SELECT PROJECT
export const RESET_SELECT_PROJECT = 'RESET_SELECT_PROJECT';

//GET PROJECT BY ID VERIFY
export const GET_PROJECT_BY_ID_VERIFY_REQ = 'GET_PROJECT_BY_ID_VERIFY_REQ';

export const GET_PROJECT_BY_ID_VERIFY_SUCCESS = 'GET_PROJECT_BY_ID_VERIFY_SUCCESS';

export const GET_PROJECT_BY_ID_VERIFY_FAIL = 'GET_PROJECT_BY_ID_VERIFY_FAIL';