//LOGIN
export const LOGIN_REQ = "LOGIN_REQ";

export const LOGIN_SUCESS = "LOGIN_SUCCESS";

export const LOGIN_FAILED = "LOGIN_FAILED";


//LOGOUT
export const LOGOUT_REQ = "LOGOUT_REQ";

export const LOGOUT_SUCESS = "LOGOUT_SUCCESS";


//REGISTER
export const REGISTER_REQ = "REGISTER_REQ";

export const REGISTER_SUCCESS = "REGISTER_SUCCESS";

export const REGISTER_FAILED = "REGISTER_FAILED";

export const RESET_REGISTER = "RESET_REGISTER";

//SEND MAIL RESET PASSWORD
export const SEND_MAIL_RESET_PASSWORD_REQ = "SEND_MAIL_RESET_PASSWORD_REQ";

export const SEND_MAIL_RESET_PASSWORD_SUCCESS = "SEND_MAIL_RESET_PASSWORD_SUCCESS";

export const SEND_MAIL_RESET_PASSWORD_FAILED = "SEND_MAIL_RESET_PASSWORD_FAILED";

export const RESET_SEND_MAIL_RESET_PASSWORD = "RESET_SEND_MAIL_RESET_PASSWORD";

//GET CURRENT USER
export const CONFIRM_RESET_PASSWORD_REQ = "CONFIRM_RESET_PASSWORD_REQ";

export const CONFIRM_RESET_PASSWORD_SUCCESS = "CONFIRM_RESET_PASSWORD_SUCCESS";

export const CONFIRM_RESET_PASSWORD_FAILED = "CONFIRM_RESET_PASSWORD_FAILED";

export const RESET_CONFIRM_RESET_PASSWORD = "RESET_CONFIRM_RESET_PASSWORD";