// GET ALL NOTIFICATIONS REQ
export const GET_ALL_NOTIFICATIONS_REQ = "GET_ALL_NOTIFICATIONS_REQ";

export const GET_ALL_NOTIFICATIONS_SUCCESS = "GET_ALL_NOTIFICATIONS_SUCCESS";

export const GET_ALL_NOTIFICATIONS_FAILED = "GET_ALL_NOTIFICATIONS_FAILED";

//SELECT A NOTIFICATION
export const SELECT_NOTIFICATION = "SELECT_NOTIFICATION";

//CREATE A NEW NOTIFICATION
export const ADD_NEW_NOTIFICATION_REQ = "ADD_NEW_NOTIFICATION_REQ";

export const ADD_NEW_NOTIFICATION_SUCCESS = "ADD_NEW_NOTIFICATION_SUCCESS";

export const ADD_NEW_NOTIFICATION_FAILED = "ADD_NEW_NOTIFICATION_FAILED";

export const RESET_ADD_NEW_NOTIFICATION = "RESET_ADD_NEW_NOTIFICATION";


//UPDATE A NEW NOTIFICATION
export const UPDATE_NOTIFICATION_REQ = "UPDATE_NOTIFICATION_REQ";

export const UPDATE_NOTIFICATION_SUCCESS = "UPDATE_NOTIFICATION_SUCCESS";

export const UPDATE_NOTIFICATION_FAILED = "UPDATE_NOTIFICATION_FAILED";

export const RESET_UPDATE_NOTIFICATION = "RESET_UPDATE_NOTIFICATION";

//DELETE A NEW NOTIFICATION
export const DELETE_NOTIFICATION_REQ = "DELETE_NOTIFICATION_REQ";

export const DELETE_NOTIFICATION_SUCCESS = "DELETE_NOTIFICATION_SUCCESS";

export const DELETE_NOTIFICATION_FAILED = "DELETE_NOTIFICATION_FAILED";

export const RESET_DELETE_NOTIFICATION = "RESET_DELETE_NOTIFICATION";

//GET NOTIFICATION BY ID 
export const GET_NOTIFICATION_BYID_REQ = "GET_NOTIFICATION_BYID_REQ";

export const GET_NOTIFICATION_BYID_SUCCESS = "GET_NOTIFICATION_BYID_SUCCESS";

export const GET_NOTIFICATION_BYID_FAILED = "GET_NOTIFICATION_BYID_FAILED";
