// GET ALL TESTPLAN REQ
export const GET_ALL_TESTPLAN_REQ = "GET_ALL_TESTPLAN_REQ";

export const GET_ALL_TESTPLAN_SUCESS = "GET_ALL_TESTPLAN_SUCESS";

export const GET_ALL_TESTPLAN_FAILED = "GET_ALL_TESTPLAN_FAILED";

//SELECT A TESTPLAN
export const SELECT_TESTPLAN = "SELECT_TESTPLAN";

//CREATE A NEW TESTPLAN
export const ADD_NEW_TESTPLAN_REQ = "ADD_NEW_TESTPLAN_REQ";

export const ADD_NEW_TESTPLAN_SUCCESS = "ADD_NEW_TESTPLAN_SUCCESS";

export const ADD_NEW_TESTPLAN_FAILED = "ADD_NEW_TESTPLAN_FAILED";

export const RESET_ADD_NEW_TESTPLAN = "RESET_ADD_NEW_TESTPLAN";

//UPDATE TESTPLAN
export const UPDATE_TESTPLAN_REQ = "UPDATE_TESTPLAN_REQ";

export const UPDATE_TESTPLAN_SUCCESS = "UPDATE_TESTPLAN_SUCCESS";

export const UPDATE_TESTPLAN_FAILED = "UPDATE_TESTPLAN_FAILED";

export const RESET_UPDATE_TESTPLAN = "RESET_UPDATE_TESTPLAN";

// GET ALL ACTIVE_TESTPLAN REQ
export const GET_ALL_ACTIVE_TESTPLAN_REQ = "GET_ALL_ACTIVE_TESTPLAN_REQ";

export const GET_ALL_ACTIVE_TESTPLAN_SUCESS = "GET_ALL_ACTIVE_TESTPLAN_SUCESS";

export const GET_ALL_ACTIVE_TESTPLAN_FAILED = "GET_ALL_ACTIVE_TESTPLAN_FAILED";

//DELETE TESTPLAN
export const DELETE_TESTPLAN_REQ = "DELETE_TESTPLAN_REQ";

export const DELETE_TESTPLAN_SUCCESS = "DELETE_TESTPLAN_SUCCESS";

export const DELETE_TESTPLAN_FAILED = "DELETE_TESTPLAN_FAILED";

export const RESET_DELETE_TESTPLAN = "RESET_DELETE_TESTPLAN";