// GET ALL TESTPLAN REQ
export const GET_ALL_TESTPLAN_REQ = "GET_ALL_TESTPLAN_REQ";

export const GET_ALL_TESTPLAN_SUCESS = "GET_ALL_TESTPLAN_SUCESS";

export const GET_ALL_TESTPLAN_FAILED = "GET_ALL_TESTPLAN_FAILED";

//SELECT A TESTPLAN
export const SELECT_TESTPLAN = "SELECT_TESTPLAN";

//CREATE A NEW TESTPLAN
export const ADD_NEW_TESTPLAN_REQ = "ADD_NEW_TESTPLAN_REQ";

export const ADD_NEW_TESTPLAN_SUCCESS = "ADD_NEW_TESTPLAN_SUCCESS";

export const ADD_NEW_TESTPLAN_FAILED = "ADD_NEW_TESTPLAN_FAILED";

//UPDATE TESTPLAN
export const UPDATE_TESTPLAN_REQ = "UPDATE_TESTPLAN_REQ";

export const UPDATE_TESTPLAN_SUCCESS = "UPDATE_TESTPLAN_SUCCESS";

export const UPDATE_TESTPLAN_FAILED = "UPDATE_TESTPLAN_FAILED";