// GET ALL MILESTONES REQ
export const GET_ALL_MILESTONES_REQ = "GET_ALL_MILESTONES_REQ";

export const GET_ALL_MILESTONES_SUCCESS = "GET_ALL_MILESTONES_SUCCESS";

export const GET_ALL_MILESTONES_FAILED = "GET_ALL_MILESTONES_FAILED";

//SELECT A MILESTONE
export const SELECT_MILESTONE = "SELECT_MILESTONE";

//CREATE A NEW MILESTONE
export const ADD_NEW_MILESTONE_REQ = "ADD_NEW_MILESTONE_REQ";

export const ADD_NEW_MILESTONE_SUCCESS = "ADD_NEW_MILESTONE_SUCCESS";

export const ADD_NEW_MILESTONE_FAILED = "ADD_NEW_MILESTONE_FAILED";

export const RESET_ADD_NEW_MILESTONE = "RESET_ADD_NEW_MILESTONE";


//UPDATE A NEW MILESTONE
export const UPDATE_MILESTONE_REQ = "UPDATE_MILESTONE_REQ";

export const UPDATE_MILESTONE_SUCCESS = "UPDATE_MILESTONE_SUCCESS";

export const UPDATE_MILESTONE_FAILED = "UPDATE_MILESTONE_FAILED";

export const RESET_UPDATE_MILESTONE = "RESET_UPDATE_MILESTONE";

//DELETE A NEW MILESTONE
export const DELETE_MILESTONE_REQ = "DELETE_MILESTONE_REQ";

export const DELETE_MILESTONE_SUCCESS = "DELETE_MILESTONE_SUCCESS";

export const DELETE_MILESTONE_FAILED = "DELETE_MILESTONE_FAILED";

export const RESET_DELETE_MILESTONE = "RESET_DELETE_MILESTONE";

//GET MILESTONE BY ID 
export const GET_MILESTONE_BYID_REQ = "GET_MILESTONE_BYID_REQ";

export const GET_MILESTONE_BYID_SUCCESS = "GET_MILESTONE_BYID_SUCCESS";

export const GET_MILESTONE_BYID_FAILED = "GET_MILESTONE_BYID_FAILED";
