// GET ALL TESTCASE REQ
export const GET_ALL_TESTCASE_REQ = "GET_ALL_TESTCASE_REQ";

export const GET_ALL_TESTCASE_SUCESS = "GET_ALL_TESTCASE_SUCESS";

export const GET_ALL_TESTCASE_FAILED = "GET_ALL_TESTCASE_FAILED";