// GET ALL TESTCASE REQ
export const GET_ALL_TESTCASE_REQ = "GET_ALL_TESTCASE_REQ";

export const GET_ALL_TESTCASE_SUCESS = "GET_ALL_TESTCASE_SUCESS";

export const GET_ALL_TESTCASE_FAILED = "GET_ALL_TESTCASE_FAILED";

// GET ALL TESTSUITE REQ
export const GET_ALL_TESTSUITE_REQ = "GET_ALL_TESTSUITE_REQ";

export const GET_ALL_TESTSUITE_SUCESS = "GET_ALL_TESTSUITE_SUCESS";

export const GET_ALL_TESTSUITE_FAILED = "GET_ALL_TESTSUITE_FAILED";


// ADD  TESTSUITE REQ
export const ADD_TEST_SUITE_REQ = "ADD_TEST_SUITE_REQ";

export const ADD_TEST_SUITE_SUCCESS = "ADD_TEST_SUITE_SUCCESS";

export const ADD_TEST_SUITE_FAILED = "ADD_TEST_SUITE_FAILED";

export const RESET_ADD_TEST_SUITE = "RESET_ADD_TEST_SUITE";

//ADD TEST CASE REQ
export const ADD_TEST_CASE_REQ = "ADD_TEST_CASE_REQ";

export const ADD_TEST_CASE_SUCCESS = "ADD_TEST_CASE_SUCCESS";

export const ADD_TEST_CASE_FAILED = "ADD_TEST_CASE_FAILED";

export const RESET_ADD_TEST_CASE = "RESET_ADD_TEST_CASE";

// GET ALL TESTSUITE REQ
export const GET_ALL_TESTSUITE_NO_TREE_REQ = "GET_ALL_TESTSUITE_NO_TREE_REQ";

export const GET_ALL_TESTSUITE_NO_TREE_SUCESS = "GET_ALL_TESTSUITE_NO_TREE_SUCESS";

export const GET_ALL_TESTSUITE_NO_TREE_FAILED = "GET_ALL_TESTSUITE_NO_TREE_FAILED";

//UPDATE A NEW TESTCASE
export const UPDATE_TESTCASE_REQ = "UPDATE_TESTCASE_REQ";

export const UPDATE_TESTCASE_SUCCESS = "UPDATE_TESTCASE_SUCCESS";

export const UPDATE_TESTCASE_FAILED = "UPDATE_TESTCASE_FAILED";

export const RESET_UPDATE_TESTCASE = "RESET_UPDATE_TESTCASE";

//DELETE A NEW TESTCASE
export const DELETE_TESTCASE_REQ = "DELETE_TESTCASE_REQ";

export const DELETE_TESTCASE_SUCCESS = "DELETE_TESTCASE_SUCCESS";

export const DELETE_TESTCASE_FAILED = "DELETE_TESTCASE_FAILED";

export const RESET_DELETE_TESTCASE = "RESET_DELETE_TESTCASE";

//GET LIST TESTCASE SELECT
export const GET_LIST_TESTCASE_SELECT_REQ = "GET_LIST_TESTCASE_SELECT_REQ";

export const GET_LIST_TESTCASE_SELECT_SUCCESS = "GET_LIST_TESTCASE_SELECT_SUCCESS";

export const GET_LIST_TESTCASE_SELECT_FAILED = "GET_LIST_TESTCASE_SELECT_FAILED";

export const RESET_LIST_TESTCASE_SELECT = 'RESET_LIST_TESTCASE_SELECT';

//UPDATE A NEW TESTSUITE
export const UPDATE_TESTSUITE_REQ = "UPDATE_TESTSUITE_REQ";

export const UPDATE_TESTSUITE_SUCCESS = "UPDATE_TESTSUITE_SUCCESS";

export const UPDATE_TESTSUITE_FAILED = "UPDATE_TESTSUITE_FAILED";

export const RESET_UPDATE_TESTSUITE = "RESET_UPDATE_TESTSUITE";

//DELETE A NEW TESTSUITE
export const DELETE_TESTSUITE_REQ = "DELETE_TESTSUITE_REQ";

export const DELETE_TESTSUITE_SUCCESS = "DELETE_TESTSUITE_SUCCESS";

export const DELETE_TESTSUITE_FAILED = "DELETE_TESTSUITE_FAILED";

export const RESET_DELETE_TESTSUITE = "RESET_DELETE_TESTSUITE";

//SEARCH TESTCASE
export const SEARCH_TESTCASE_REQ = "SEARCH_TESTCASE_REQ";

export const SEARCH_TESTCASE_SUCCESS = "SEARCH_TESTCASE_SUCCESS";

export const SEARCH_TESTCASE_FAILED = "SEARCH_TESTCASE_FAILED";

//export const RESET_SEARCH_TESTCASE = "RESET_SEARCH_TESTCASE";

//UPLOAD TESTCASE
export const UPLOAD_TESTCASE_REQ = "UPLOAD_TESTCASE_REQ";

export const UPLOAD_TESTCASE_SUCCESS = "UPLOAD_TESTCASE_SUCCESS";

export const UPLOAD_TESTCASE_FAILED = "UPLOAD_TESTCASE_FAILED";

export const RESET_UPLOAD_TESTCASE = "RESET_UPLOAD_TESTCASE";