// GET ALL TESTCASE REQ
export const GET_ALL_TESTCASE_REQ = "GET_ALL_TESTCASE_REQ";

export const GET_ALL_TESTCASE_SUCESS = "GET_ALL_TESTCASE_SUCESS";

export const GET_ALL_TESTCASE_FAILED = "GET_ALL_TESTCASE_FAILED";

// GET ALL TESTSUITE REQ
export const GET_ALL_TESTSUITE_REQ = "GET_ALL_TESTSUITE_REQ";

export const GET_ALL_TESTSUITE_SUCESS = "GET_ALL_TESTSUITE_SUCESS";

export const GET_ALL_TESTSUITE_FAILED = "GET_ALL_TESTSUITE_FAILED";


// ADD  TESTSUITE REQ
export const ADD_TEST_SUITE_REQ = "ADD_TEST_SUITE_REQ";

export const ADD_TEST_SUITE_SUCCESS = "ADD_TEST_SUITE_SUCCESS";

export const ADD_TEST_SUITE_FAILED = "ADD_TEST_SUITE_FAILED";

//ADD TEST CASE REQ
export const ADD_TEST_CASE_REQ = "ADD_TEST_CASE_REQ";

export const ADD_TEST_CASE_SUCCESS = "ADD_TEST_CASE_SUCCESS";

export const ADD_TEST_CASE_FAILED = "ADD_TEST_CASE_FAILED";

// GET ALL TESTSUITE REQ
export const GET_ALL_TESTSUITE_NO_TREE_REQ = "GET_ALL_TESTSUITE_NO_TREE_REQ";

export const GET_ALL_TESTSUITE_NO_TREE_SUCESS = "GET_ALL_TESTSUITE_NO_TREE_SUCESS";

export const GET_ALL_TESTSUITE_NO_TREE_FAILED = "GET_ALL_TESTSUITE_NO_TREE_FAILED";

//UPDATE A NEW TESTCASE
export const UPDATE_TESTCASE_REQ = "UPDATE_TESTCASE_REQ";

export const UPDATE_TESTCASE_SUCCESS = "UPDATE_TESTCASE_SUCCESS";

export const UPDATE_TESTCASE_FAILED = "UPDATE_TESTCASE_FAILED";

//DELETE A NEW TESTCASE
export const DELETE_TESTCASE_REQ = "DELETE_TESTCASE_REQ";

export const DELETE_TESTCASE_SUCCESS = "DELETE_TESTCASE_SUCCESS";

export const DELETE_TESTCASE_FAILED = "DELETE_TESTCASE_FAILED";
